version: '3.8'

services:
  app:
    env_file:
      - .env
    build: ./docker/php
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql

    networks:
      - app-network

  mysql:
    env_file:
      - .env
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql-files/
    ports:
      - "${DB_PORT}:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local