version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
    ports:
      - "${MYSQL_PORT}:3306"